authentication.go
gerrit.go

This should resolve andygrunwald/go-gerrit#5

Add support for digest based authentication

---

changes.go

This PR contains two bug fixes.  First it updates `ListChangeComments` to query the correct endpoint (it was `changes/<change id>/in`).
Second,`ListChangeDrafts` and `ListChangeComments` were expecting a response from Gerrit like this:
```
{
"file1": {<comment1>},
"file2": {<comment2>},
}
```
When in fact Gerrit will send this:
```
{
"file1": [{<comment1>}, {<comment2>}],
"file2": [{<comment3>}, {<comment4>}]
}
```
References:
* https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#list-change-comments
* https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#list-change-drafts

Bug fixes for ListChangeDrafts and ListChangeComments

---

README.md
events.go
events_test.go
gerrit.go
gerrit_test.go

This PR adds support for querying information about Gerrit events via the optional events-log plugin.  The structures this PR adds could also be used when parsing output from the built-in `gerrit stream-events` command over ssh.

Add support for querying the events-log plugin

---

authentication.go
gerrit.go

According to RFC2617 3.2.2.3 A2, 'If the "qop" directive's
value is "auth" or is unspecified, then A2 is':
```
A2       = Method ":" digest-uri-value
```
Before this commit 'Method' was always GET even if
the request was a POST, PUT, etc.
For some reason, this bug has only posed a problem
for SetReview.  In other cases Gerrit seems to accept
the request rather than returning 401 Unauthorized.

A2 hash should use the request's method (closes #13)

---

CHANGELOG.md
changes.go

The use of `http.StatusConflict` does not change how the code functions, it just makes it easier to read.

Use http.StatusConflict instead of hard coded value in SubmitChange

---

CHANGELOG.md
accounts.go

Make _account_id optional in AccountInfo

---

CHANGELOG.md
gerrit.go
gerrit_test.go

This PR updates `NewClient` to handle credentials in the url:
```go
client, err := gerrit.NewClient("http://user:secret@host:port/")
```
If the credentials are invalid then `err` will be set appropriately. This new function will be used in the `docker_tests` branch.
Another case were this could be useful is when a consumer of go-gerrit is using configuration files to drive their application. In these cases code could go from:
```go
username, password := GetCredentials()
client, err := gerrit.NewClient(GetURL())
client.Authentication.SetDigestAuth(username, password)
// test auth
```
To:
```go
client, err := gerrit.NewClient(GetURL())
// make sure err == nil
```

Update NewClient handle credentials in the url

---

CHANGELOG.md
changes_test.go
gerrit.go

Query url parameters should not escape + or :

---

CHANGELOG.md
changes.go

This field is usually included as as part of an event from the events-log plugin.

Add the missing URL field to ChangeInfo

---

CHANGELOG.md
events.go
events_test.go

This PR improves `GetEvents()` with a few changes:
- Update EventInfo to handle the `changeKey` field and apply the proper type for the Project field (e24573d)
- Provide a means to ignore marshaling errors (ac5aca8)
- Update GetEvents() to return the failed lines and remove the pointer to the return value because it's unnecessary (bf5e285).

Fixes and Improvements for GetEvents()

---

CHANGELOG.md
changes.go

This is a small but **breaking change** to support labels other than `Code-Review` and `Verified`.  
See #21 for a full discussion.

Support Custom Labels

---

changes.go

Without the trailing slash, I get a 404 from the Gerrit instance running at https://chromium-review.googlesource.com/

fix path for CreateChange call

---

changes_edit.go
changes_test.go

This fixes a 400 I was getting when calling PublishChangeEdit on chromium-review.googlesource.com. It told me it expected a json body, so this adds one.

update PublishChangeEdit: notify param

---

changes_edit.go
changes_test.go
gerrit.go
gerrit_test.go

Another fix for making changes on chromium-review.googlesource.com.
This allows the caller to pass the new file contents as a string.

Fix ChangeFileContentInChangeEdit

---

changes.go

Just testing the waters with a small documentation fix that I ran into.
Thank you for making this library (and making its API similar to go-github), I was really glad this already existed!

Fix Gerrit API docs link for ChangesService.GetChangeDetail.

---

gerrit.go

This PR implements a suggestion from https://github.com/andygrunwald/go-gerrit/pull/10/files#r116843309.
If body has `")]}'\n"` prefix, there's no need to use `bytes.IndexByte` to find the first `'\n'` character, it's known to be at index 4 because `bytes.HasPrefix(body, []byte(")]}'\n"))` was true.
Since this is called often, it's probably a good idea to factor out `[]byte(")]}'\n")` into a package scope variable, instead of potentially allocating once per `RemoveMagicPrefixLine` call.

Simplify and optimize RemoveMagicPrefixLine.

---

events.go
types.go
types_test.go

Depending on the version of the events-log plugin
and the version of Gerrit you can end up in a situation
where some values of EventInfo.PatchSet.Number are a
string and other are an integer. This change works around
the problem by replacing the Number field with a custom
type that can handle either strings or integers.
Note, this does not change the underlying type of the
Number field.

Fix type of EventInfo.PatchSet.Number

---

CHANGELOG.md
gerrit.go
gerrit_test.go

See commit ba033b0 for an explanation.

NewClient() can't handle credentials containing characters such as /

---

CHANGELOG.md
changes.go
changes_reviewer.go
changes_revision.go

The REST api for Gerrit states that:
As response a ReviewResult entity is returned that describes the
applied labels and any added reviewers (e.g. yourself, if you set
a label but weren’t previously a reviewer on this CL).
go-gerrit however was returning a ReviewInfo entity that was missing
the reviewers and ready fields.

SetReview should return a ReviewResult

---

CHANGELOG.md
changes.go
changes_test.go

Discovered AbandonChange was missing when I was working on [Change.Abandon()](https://github.com/opalmer/gerrittest/commit/72bedb205cc02d0fba3547f6f37edbc26021bf56#diff-a1b195d80625ef162eb4bf5d2a6cceb4R124) in gerrittest. Figured I'd implement it in go-gerrit and the other missing functions too since they're nearly identical.

Add missing AbandonChange, RebaseChange, RestoreChange and RevertChange

---

CHANGELOG.md
gerrit.go
gerrit_test.go

Previously checkAuth() would fail if the socket
we expected to find Gerrit running on didn't
have anything listning. This would result in
the connection be refused and no response being
sent from GetAccount().
The checkAuth() function was always expecting
some kind of response which in turn caused the
panic.

Fix panic in checkAuth() if Gerrit is down

---

changes.go

DiffContent.A/B/AB should be []string instead of string.
DiffIntralineInfo should be [][2]int.

Fixed #44.

---

.travis.yml
README.md
changes.go
changes_revision.go
changes_revision_test.go
changes_test.go

Modify ListFilesReviewed to return a slice of strings, rather than slice of FileInfos. This matches its actual behavior (according to documentation; I haven't tested against a real API because it requires auth).
Modify both ListFiles and ListFilesReviewed to return map/slice directly, rather than a pointer to one. There doesn't appear to be any value in returning a pointer, it just makes the API harder to use. Slice/map are already reference types.
Modify all endpoints to escape fileID parameter so it can be safely placed inside a URL path segment.
Make note of Base parameter being undocumented for ListFiles endpoints. However, it has been tested and it works (it's a very important parameter to support).
Add missing fields to ChangeMessageInfo, FileInfo.
Add tests for ListFiles, …

Add FilesOptions to ListFiles, ListFilesReviewed; add missing fields.

---

accounts.go
changes.go
groups.go
projects_tag.go
types.go
types_test.go

This is a breaking API change. It improves usability of time fields by automatically parsing them into a `time.Time`-like type.
Pointers are used for optional fields, so that the `,omitempty` option correctly omits them when they have zero value (i.e., `nil`). This can't be done with values at this time (see golang/go#11939).
Resolves #55.
I used [Gerrit REST API Documentation](https://gerrit-review.googlesource.com/Documentation/rest-api.html) to find which fields are a timestamp. I hope I got them all.

Use Timestamp type for all time fields.

---

changes.go
gerrit.go

The motivation for doing this is as follows.
`NewClient` takes a `gerritURL` string, which is then parsed into a `baseURL` internal to the `gerrit.Client`.
Some users of `gerrit.Client` may need to know the Gerrit instance that the client targets. Currently, they'd have to be provided the target separately, which can lead to a mismatch from the actual `gerrit.Client` Gerrit instance:
```Go
client, err := gerrit.NewClient("https://go-review.googlesource.com/", nil)
if err != nil {
return err
}
service := gerritapi.NewService(client, "https://upspin-review.googlesource.com/") // mismatch
```
`BaseURL` method is added to allow users to find out the Gerrit URL endpoint directly from the `gerrit.Client`, removing the chance for any mismatches:
```Go
client, err := …
```

Expose the client's BaseURL.

---

changes.go

Add Reviewers field to ChangeInfo
from:
https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#change-info
Right now, this is the only field missing from the entities that I need to finish up creating a Gerrit widget on  https://github.com/senorprogrammer/wtf

Add Reviewers field to ChangeInfo

---

authentication.go
changes.go

This PR makes the TravisCI build green again. In detail
* Rename struct fields to Go naming convention (golint)
* Renamed the gometalinter `gas` to `gosec`
* Fixed the handing of an unhandled error
One important note: The renaming of struct fields is a breaking change. It was introduced in https://github.com/andygrunwald/go-gerrit/pull/60. @achew22 would be nice if you can check this as well, because it might break your code.

Make TravisCI build green again

---

projects_commit.go

The method was accidentally duplicating GetBranchContent.

Fix GetCommitContent to actually get commit content

---

projects_branch.go
projects_test.go

branch can also have slashes in the name, aka, branch: foo/bar/baz is valid, but need to be escaped when calling the gerrit rest api.

escape branch names in the query as well

---

.travis.yml
Makefile
README.md

Update README to mention current minimum Go version.
Remove non-existent .PHONY rules from Makefile.
This change fixes CI, which is currently [broken](https://travis-ci.org/andygrunwald/go-gerrit/builds/549446647).
/cc @andygrunwald

drop support for Go 1.9, add Go 1.12

---

changes.go
changes_test.go

Thanks for your excellent Gerrit API client! I wish Google offered something like this.

add support for Change API's "Set Commit Message" endpoint

---

changes.go

MoveChange allows to move changes between branches.

Add Changes.MoveChange

---

changes.go

Set `omitempty` for `AbandonInput.Notify` and `AbandonInput.NotifyDetails` fields.
The reason for this change is that if `NotifyDetails` is not set, `notify_details` will be unmarshalled as `nill` in the json string, which isn't allowed by the Gerrit server and will result in a `400 Bad Request` response.

omitempty for AbandonInput.Notify and AbandonInput.NotifyDetails fields

---

changes.go

These are from https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#change-info

Add more supported fields to the ChangeInfo struct

---

gerrit.go

fix: no need to send content-type header if no header sent

---

projects.go

This will stop a mostly-default ProjectInput from generating a number
of empty fields in the JSON payload that confuse gerrit, e.g.
{ "use_signed_off_by": "" }
This is a fix for issue #93.

fix: omit optional empty fields in ProjectInput

---

changes.go

It was reported in #77 that the delete-draft-change API referenced in
the docs no longer exists. As suggested in the issue, just rename to
to Changes.DeleteChange.

changes: rename Changes.DeleteDraftChange to DeleteChange

---

changes.go
changes_test.go

The API docs refer to the ChangeInput entity for create-change, see
[Documentation/rest-api-changes.html#change-input](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#change-input).
Rename the existing CreateChange(ChangeInfo) method to
CreateChangeDeprecated and add a new CreateChange(ChangeInput)
implementation. Also added a test that ensures that none of the JSON
payload strings are empty strings (gerrit does not like those).

api: deprecate CreateChange using ChangeInfo (use ChangeInput instead)

---

changes.go
changes_test.go

The ChangeInput type was recently added with just the bare-bones
fields in place. This commit adds the rest of the fields per the
current gerrit documentation.
Updated TestChangesService_CreateChange to have stronger assertions
about empty values (recursively checks nested structures), and added
test cases specific to exercise ChangeInput.Merge and
ChangeInput.Author.
This change is a result of the discussion on PR #96.

changes: fill in the rest of Changes.ChangeInput

---

changes_revision.go

Remove a extra characters in url path.

fix: remove a extra characters in url path

---

changes.go
changes_test.go

This PR adds `gerrit.ChangesService.SetReadyForReview()`.

Add support for Change API's "Set Ready-For-Review" endpoint

---

projects_commit.go
projects_commit_test.go

GetIncludeIn Retrieves the branches and tags in which a change is included.
Branches that are not visible to the calling user according to the project’s read permissions are filtered out from the result.
Gerrit API docs: https://gerrit-review.googlesource.com/Documentation/rest-api-projects.html#get-included-in

add: project commits included in

---

changes.go
doc.go

(see commit messages - please do not squash)

apply gofmt, add new fields to ReviewInput

---

changes.go

The `kind` field is missing in `RevisionInfo`. The field is important because users can use this info for a general description of what are changed in the revision.

Add revision kind to RevisionInfo

---

projects.go

delete-project is one of the blessed gerrit plugins.  This change enables us to use it to delete existing projects.

Add support for project deletion (with plugin)

---

changes.go

RebaseInput is relatively big at this point; the main field I'm interested in is actually just `on_behalf_of_uploader`, but there are several options missing from go-gerrit
https://gerrit.googlesource.com/gerrit/+/refs/heads/master/java/com/google/gerrit/extensions/api/changes/RebaseInput.java
https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#rebase-input

Support more options for rebasing changes

---

changes.go

Introduced in https://gerrit-review.googlesource.com/c/gerrit/+/376877.
Documented at https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#parent-info.
It is especially helpful to efficiently query for mergable chains.

Implement parents_data in RevisionInfo

---

changes.go

The example provided at:
https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#set-review
uses ints for the label values, not strings.  This change lines ReviewInput up with that example.

Change ReviewInput to use map[string]int for labels

---

changes.go

Since Gerrit 3.4.0, the MoveInput field has been `keep_all_votes` and not `keep_all_labels`. This change makes the MoveInput struct reflect that.

Fix MoveInput struct definition (keep_all_labels -> keep_all_votes)

---

changes.go

New fields have been added to SubmitInput to support features such as submitting on behalf of other users, and notification handling. The fields have been all listed as optional to match the current API (as of 3.8+). I'm open to removing  WaitForMerge as well, but that would make this a breaking change.

Update SubmitInput entity to support new fields

---

changes.go

As Gerrit had deprecated label functions and migrate to submit-requirements (https://gerrit-review.googlesource.com/Documentation/config-labels.html), our project (Prow, https://docs.prow.k8s.io/docs/overview/) needs to get this submit-requirements info associated with a change.

Add support for submit_requirements fields in ChangeInfo.
